### ISSUE TITLE
some questions and suggestions

### ISSUE THREAD

**Issue by tttousa** [drbh/wasm-fingerprint#3]
Hello！
Thanks for your reply ! I've run the web-example successfully!
I love your project！ And I have some other questions~ I'll appreciate it if you can give me a reply~
（1）I notice that your source codes are based Rust and I've learned that wasm can also support C /C++,so why choose Rust ? I wonder whether your project can be implemented in C/C++ source code.
（2）As a student, I wonder whether wasm_fingerprint_mod.js and wasm_fingerprint_bg.wasm are written by yourself or auto-generated. If you write the wasm_fingerprint_mod.js，I want to learn how to write it！
（3）I have a little suggestions. As far as I know，there are other fingerprint methods other than canvas，such as webGL，webAudio，clock skew and so on. So,maybe you can have a try to enrich your wasm-fingerprint with these methods !
Finally, Thank you! You are so nice and I love your project !!!

**Comment by drbh** [comment]
Hey @tttousa 

Thank you for the interest!

1) There are many reason why I chose Rust and choose Rust for other projects aside from this. However I don't want to weigh you down with my Rust excitement and I think you'd benefit more from a series of facts - that I think make Rust a good choice.
- Rust has nice tools for compiling to `wasm`
- [wasm-pack](https://github.com/rustwasm/wasm-pack) will compile rust to `wasm` and generate `JS` wrappers/shims
- wasm_bindgen which is part of wasm-pack will handle generate all of the connections between the browsers API's like canvas and manipulating the DOM

I'm sure the same logic can be implemented in C or C++ or any other language - I can't speak to the bindings between Canvas and C++ WASM binaries..

2) Both of those files are auto generated (with the exception to come changes in `wasm_fingerprint_mod.js`) note the `_bg` which stands for bindgen, which creates these files. The reason I added `_mod` to the first file is because I modified lines ~405:415 to allow wasm-fingerprint to bind to the window when its dont loading. This is done for the end user's convenience and to make the lib easy to use.


3) Those all sound really interesting and promising! Maybe you can share how those methods would work? Like how do you create a fingerprint from `clock skew`? or any of the other metrics. In this project we essentially draw a picture then get its bit value and use that to create a fingerprint. How does that work with webAudio? 

Looking forward to your feedback and ideas!

**Comment by tttousa** [comment]
@drbh  Hello！
Thank you for the reply！Your replys help me a lot！
1. I‘m a new comer in  the field of Rust，so I have difficulty in reading the Rust file such as the /src/lib.rs (used to make canvas fingerprint). Can you provide me your Javascript source code of canvas fingerprint ? That will help me understand better~~ And I can also make a performance test between the Js version and the rust-wasm version at the execution speed or code size and so on. 
2. I want to learn about rust-wasm to implement more fingerprint methods~ Can you recommend me some study materials such as websites. 
3. About other fingerprint methods, there are several methods in https://github.com/AJLoveChina/fingerprintDemo/tree/master/src/core
https://github.com/Valve/fingerprintjs2.
There are many papers in the web fingerprint field :
Clock around the clock: Time-based device fingerprinting (clock skew)
(Cross-)Browser Fingerprinting via OS and Hardware Level (webGL)
So you can do more in your wasm-fingerprint ! And I want to join you in this field and learn knowledge~
Looking forward to your feedback！Thank you！

**Comment by drbh** [comment]
@tttousa Hey there

No need to make a new issue, we can continue the conversation in this thread. 

1. I think this is a great opportunity to learn some Rust! The code in `/src/lib.rs` is a single file and all of the variable are well named. Read the ~30 lines in the function [fn make_fingerprint](https://github.com/drbh/wasm-fingerprint/blob/e30e7582fda6c5cfdb165a22e9e3c4f668ca3ff9/src/lib.rs#L17) line by line and you should be able to understand the code..

For instance 
```rust
    let window = web_sys::window().expect("should have a window in this context");
    let document = web_sys::window().unwrap().document().unwrap();
    let performance = window
        .performance()
        .expect("performance should be available");
```

Is the code that attaches to the DOM window. The next block of code draws the canvas image and the last block makes the fingerprint from the image. 

2.  In terms of understanding why this works (will help understanding the code) you should read https://browserleaks.com/canvas and their how it works section (they provide some JS examples there too)

3. Thanks for those resources - I will look into how those systems work and see if there is a good way to add this to `wasm-fingerprint`!  _The clock skew is what interests me the most next_

PS: I highly recommend learning Rust (for both fun and work). However I want to warn that this project is written is Rust but is not very Rust-like. What I mean by this - is that there are not any special Rust specific things implemented and the code itself mostly calls API's that the Browser handles. 

To get started with Rust from a more educational standpoint checkout the [Rust Book](https://doc.rust-lang.org/book/)

PPS: Please please feel free to fork the repo and try out some other fingerprinting techniques and try out Rust. 

Hope this is helpful

**Comment by tttousa** [comment]
Thank you very much！！！
